### ISSUE TITLE
Error al instalar 

### ISSUE THREAD

**Issue by mbanco** [FoxShell/kodnet#1]
James,
Instale @kawix/core sin problemas, pero cuando ejecuto el cmd: kwcore gh+/voxsoftware/packages/kodnet/0.0.1.kwa me muestra el siguiente error:

![Captura](https://user-images.githubusercontent.com/7707490/68873474-7a256980-06de-11ea-8676-d46fe7c3e56d.PNG)

Saludos cordiales

**Comment by voxsoftware** [comment]
Hi, now is solved, check the readme for new step
