### ISSUE TITLE
Dictionary<string, string> object pass to C# method from VFP

### ISSUE THREAD

**Issue by elesh9** [FoxShell/kodnet#6]
i need Dictionary<string, string> object pass from VFP To C# class object to manipulate some work 

<pre>
/* VFP Code  */

m.kodnetCOM = _screen.kodnetLoader.v4.COM

m.dict =  m.kodnet.getStaticWrapper("System.Collections.Generic.Dictionary<System.String,System.String>").construct()
m.dict.item["k1"] = "James"
m.dict.item["k2"] = "28"

m.oDictonaryHelper = m.kodnet.getStaticWrapper("AppBase.AppDictonaryHelper").construct()
* here need list of keys to enumerate string key and using in vfp code
m.oKeys = m.oDictonaryHelper.getStringKeys(m.dict)   && <--  parameter count error occurred
</pre>

and 
// C# code

...

``public string[] GetStringKeys(Dictionary<string, string> dict)
``        {
``
``          if (dict == null) return  new string[] { };
``
``          var retval = dict.Keys.ToArray();
``
``          return retval;
``
``       }
...

any help or suggestion  ?

**Comment by voxsoftware** [comment]
Use the generic class:

```harbour 
m.dict =  m.kodnet.getStaticWrapper("System.Collections.Generic.Dictionary<System.String,System.String>").construct()
```
